name: aesrl
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75154
title: once upon a time...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4e8d1'
    - '#72a6cf'
    - '#4e2a25'
    - '#000100'
    - '#f5ad70'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.8296205282676965
  rhythmicContrast: 0.75
purpose: []
